name: task_tracker_app
description: "A task tracker app for forgetful people with voice input, calendar integration, and chat parsing"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Database
  sqflite: ^2.3.3
  path: ^1.9.0
  
  # Voice Recognition
  speech_to_text: ^6.6.2
  permission_handler: ^11.3.1
  
  # Calendar
  table_calendar: ^3.1.2
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  
  # Date/Time
  intl: ^0.19.0
  jiffy: ^6.3.1
  
  # UI
  cupertino_icons: ^1.0.8
  
  # Navigation
  go_router: ^14.2.7
  
  # Utils
  uuid: ^4.5.1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true