name: task_tracker_app
description: "A task tracker app for forgetful people with voice input, calendar integration, and chat parsing"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Database
  sqflite: ^2.4.2
  path: ^1.9.1
  
  # Voice Recognition
  speech_to_text: ^7.2.0
  permission_handler: ^12.0.2
  
  # Calendar
  table_calendar: ^3.2.0
  
  # Notifications
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  
  # Date/Time
  intl: ^0.20.1
  jiffy: ^6.4.0
  
  # UI
  cupertino_icons: ^1.0.8
  
  # Navigation
  go_router: ^16.0.0
  
  # Utils
  uuid: ^4.5.1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code generation and serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  build_runner: ^2.4.13
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  
  # Database testing
  sqflite_common_ffi: ^2.4.2+2
  
  # Code generation (freezed support)
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true