name: task_tracker_app
description: "A task tracker app for forgetful people with voice input, calendar integration, and chat parsing"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Voice Recognition
  speech_to_text: ^6.6.0
  permission_handler: ^11.2.0
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  
  # Date/Time
  intl: ^0.19.0
  jiffy: ^6.2.1
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Utils
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true